name: Node

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    name: eslint node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-versions }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    name: build node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-versions }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present
